### ISSUE TITLE
Node commissioning tasks status messages should be part of 'clusterctl node c < >' 

### ISSUE THREAD

**Issue by rkharya** [contiv/cluster#103]
Currently we need to do status on clusterm.service to know about various commissioning tasks status. which is kind of inconvenient. When we run 'ansible-playbook' we do get the status message as it progresses. We need a similar way of displaying commissioning tasks status.

Thanks.

**Comment by mapuri** [comment]
Addressed by #117 

`clusterctl job get active` can now be used to see the status and logs of a running job. 

`clusterctl job get last` can be used to see the status and logs of last completed job.
