### ISSUE TITLE
Node de-commissioning stuck forever, need a recovery mechanism

### ISSUE THREAD

**Issue by rkharya** [contiv/cluster#114]
Steps -
1) 5 node cluster fully formed
2) Started de-commissioning from node-6 backward
3) Both 5 & 6 de-commissioned successfully
4) Node-4 decommissioning started, clusterm service logs recorded serf membership error message as below -

May 03 11:42:17 Docker-1.cisco.com clusterm[21575]: level=info msg=
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=debug msg="dequeued manager event: waitableEvent: nodeDecommissioned: Docker-4-FCH19517CER"
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=debug msg="going to run playbook: \"/home/cluster-admin/ansible//cleanup.yml\" with hosts file: \"/tmp/hosts604050008\" and vars: {\"contiv_network_mode\":\"standalone\",\"contiv_network_src_file\":\"http://10.105.219.83/share/netplugin-pv0.1-04-21-2016.15-14-32.UTC.tar.bz2\",\"contiv_network_version\":\"v0.1-04-21-2016.15-14-32.UTC\",\"control_interface\":\"enp6s0\",\"docker_device\":\"/dev/sdb\",\"docker_device_size\":\"100000MB\",\"docker_version\":\"1.10.3\",\"env\":{\"HTTPS_PROXY\":\"http://64.102.255.40:8080\",\"HTTP_PROXY\":\"http://64.102.255.40:8080\",\"NO_PROXY\":\"10.105.219.83\",\"http_proxy\":\"http://64.102.255.40:8080\",\"https_proxy\":\"http://64.102.255.40:8080\",\"no_proxy\":\"10.105.219.83\"},\"fwd_mode\":\"routing\",\"netplugin_if\":\"enp7s0\",\"scheduler_provider\":\"ucp-swarm\",\"service_vip\":\"10.65.122.79\",\"ucp_license_file\":\"/home/cluster-admin/docker_subscription.lic\",\"ucp_version\":\"1.0.4\",\"validate_certs\":\"false\"}"
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and "
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="make sure become_method is 'sudo' (default)."
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="This feature will be removed in a "
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="future release. Deprecation warnings can be disabled by setting "
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="deprecation_warnings=False in ansible.cfg."
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg=
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="PLAY [all] *********************************************************************"
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg=
May 03 11:42:29 Docker-1.cisco.com clusterm[21575]: level=info msg="TASK [setup] *******************************************************************"
May 03 11:42:51 Docker-1.cisco.com clusterm[21575]: level=info msg="Event received: {Event:member-failed Members:[{Name:Docker-4-FCH19517CER Addr:10.65.122.67 Port:7946 Tags:map[NodeAddr:10.65.122.67 NodeLabel:Docker-4 NodeSerial:FCH19517CER] Status:failed ProtocolMin:1 ProtocolMax:2 ProtocolCur:2 DelegateMin:2 DelegateMax:4 DelegateCur:4}]}"
**May 03 11:42:51 Docker-1.cisco.com clusterm[21575]: level=debug msg="monitor event: {Type:Disappeared Node:0xc820339290}"
May 03 11:42:51 Docker-1.cisco.com clusterm[21575]: level=debug msg="processing monitor event: {Type:Disappeared Node:0xc820339290}"
May 03 11:42:51 Docker-1.cisco.com clusterm[21575]: level=debug msg="enqueued manager event: nodeDisappeared: &{label:Docker-4 serial:FCH19517CER addr:10.65.122.67}"
May 03 11:42:51 Docker-1.cisco.com clusterm[21575]: level=debug msg="dequeued manager event: nodeDisappeared: &{label:Docker-4 serial:FCH19517CER addr:10.65.122.67}"**

5) Node-4 Blade was not responding on KVM as well.. so had to reset it
6) Node-4 came back online successfully and got discovered also. Serf members were showing up Node-4 as alive -

[cluster-admin@Docker-1 ~]$ serf members
Docker-1-FLM19379EUC  10.65.122.64:7946  alive  NodeLabel=Docker-1,NodeSerial=FLM19379EUC,NodeAddr=10.65.122.64
Docker-2-FLM19379EU8  10.65.122.65:7946  alive  NodeLabel=Docker-2,NodeSerial=FLM19379EU8,NodeAddr=10.65.122.65
Docker-3-FCH19517CF9  10.65.122.66:7946  alive  NodeAddr=10.65.122.66,NodeLabel=Docker-3,NodeSerial=FCH19517CF9
**Docker-4-FCH19517CER  10.65.122.67:7946  alive  NodeLabel=Docker-4,NodeSerial=FCH19517CER,NodeAddr=10.65.122.67**
Docker-5-FCH19517CAT  10.65.122.68:7946  alive  NodeLabel=Docker-5,NodeSerial=FCH19517CAT,NodeAddr=10.65.122.68
Docker-6-FCH1945JJ4F  10.65.122.69:7946  alive  NodeSerial=FCH1945JJ4F,NodeAddr=10.65.122.69,NodeLabel=Docker-6

7) node de-commission task seems to be stuck now for 37 minutes and not making any progress -

May 03 12:19:29 Docker-1.cisco.com clusterm[21575]: level=debug msg="[ansible-playbook -i /tmp/hosts604050008 --user cluster-admin --private-key /home/cluster-admin/.ssh/id_rsa --extra-vars {\"contiv_network_mode\":\"standalone\",\"contiv_network_src_file\":\"http://10.105.219.83/share/netplugin-pv0.1-04-21-2016.15-14-32.UTC.tar.bz2\",\"contiv_network_version\":\"v0.1-04-21-2016.15-14-32.UTC\",\"control_interface\":\"enp6s0\",\"docker_device\":\"/dev/sdb\",\"docker_device_size\":\"100000MB\",\"docker_version\":\"1.10.3\",\"env\":{\"HTTPS_PROXY\":\"http://64.102.255.40:8080\",\"HTTP_PROXY\":\"http://64.102.255.40:8080\",\"NO_PROXY\":\"10.105.219.83\",\"http_proxy\":\"http://64.102.255.40:8080\",\"https_proxy\":\"http://64.102.255.40:8080\",\"no_proxy\":\"10.105.219.83\"},\"fwd_mode\":\"routing\",\"netplugin_if\":\"enp7s0\",\"scheduler_provider\":\"ucp-swarm\",\"service_vip\":\"10.65.122.79\",\"ucp_license_file\":\"/home/cluster-admin/docker_subscription.lic\",\"ucp_version\":\"1.0.4\",\"validate_certs\":\"false\"} /home/cluster-admin/ansible//cleanup.yml] (/usr/bin/ansible-playbook) (pid: 27136) has been running for 37m0.018523794s"

So in case of a node failure event, if someone issues node decommission flow, if the node comes back online then it should progress forward. If this is not possible, then there should be someway to recover out of this situation. Now i cannot de-commission any other node, it errors out with message. 

Full clusterm logs are attached herewith. 
[clusterm.txt](https://github.com/contiv/cluster/files/246400/clusterm.txt)

**Comment by mapuri** [comment]
@rkharya , thanks for reporting the issue

just to summarize and list what you experienced:
1. a node disappeared while decommission (for that node, `Docker-4-FCH19517CER` in this case) was in progress. This caused decommission task to be stuck.
2. During the above time user is not able to perform other tasks because clusterm thinks there is active job

`2.` is actually a correct behavior. I think `1.` is already being tracked by #63. Is there any other issue that I missed? A workaround for `1.` in short term would be to kill the ansible related PID that shows up in `systemctl status clusterm` command, which will error out the operation and let clusterm handle it gracefully.

**Comment by mapuri** [comment]
closing it, since we are tracking killing/stopping ongoing job with #63
