### ISSUE TITLE
Commissioning of a node failing inconsistently

### ISSUE THREAD

**Issue by pradvara** [contiv/cluster#148]
Commissioning of node failing with below error inconsistently.

After multiple runs the nodes status is getting moved from "Unallocated" to "Allocated"

[2:14] 
fatal: [vm13-VMware-56]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1464765591.27-160644892993135/rpm_key\", line 3052, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1464765591.27-160644892993135/rpm_key\", line 203, in main\r\n    RpmKey(module)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1464765591.27-160644892993135/rpm_key\", line 87, in __init__\r\n    keyfile = self.fetch_key(key)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1464765591.27-160644892993135/rpm_key\", line 121, in fetch_key\r\n    key = rsp.read()\r\nAttributeError: 'NoneType' object has no attribute 'read'\r\n", "msg": "MODULE FAILURE", "parsed": false}

It is also inconsistently failing while trying to download images 

    fatal: [vm15-VMware-56]: FAILED! => {"changed": true, "cmd": "docker run --rm -t --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp images --image-version=1.1.0", "delta": "0:00:57.000742", "end": "2016-06-01 15:52:25.175085", "failed": true, "rc": 1, "start": "2016-06-01 15:51:28.174343", "stderr": "", "stdout": "\u001b[34mINFO\u001b[0m[0000] Your engine version 1.10.3 is compatible     \r\n\u001b[34mINFO\u001b[0m[0000] Pulling required images... (this may take a while) \r\n\u001b[31mERRO\u001b[0m[0051] We were unable to pull one or more required images.  Please set REGISTRY_USERNAME, REGISTRY_PASSWORD, and REGISTRY_EMAIL environment variables for your Docker Hub account on this container with -e flags to run. \r\n\u001b[31mFATA\u001b[0m[0051] Error response from daemon: Get https://registry-1.docker.io/v2/docker/ucp-dsinfo/manifests/1.1.0: Gateway Timeout ", "stdout_lines": ["\u001b[34mINFO\u001b[0m[0000] Your engine version 1.10.3 is compatible     ", "\u001b[34mINFO\u001b[0m[0000] Pulling required images... (this may take a while) ", "\u001b[31mERRO\u001b[0m[0051] We were unable to pull one or more required images.  Please set REGISTRY_USERNAME, REGISTRY_PASSWORD, and REGISTRY_EMAIL environment variables for your Docker Hub account on this container with -e flags to run. ", "\u001b[31mFATA\u001b[0m[0051] Error response from daemon: Get https://registry-1.docker.io/v2/docker/ucp-dsinfo/manifests/1.1.0: Gateway Timeout "], "warnings": []}

**Comment by mapuri** [comment]
@pradvara `https://registry-1.docker.io/v2/docker/ucp-dsinfo/manifests/1.1.0: Gateway Timeout` indicates that the docker registry was not reachable . 

Usually these errors are intermittent and go away with subsequent retries or as the repositories become available. 

I will close this as there is nothing that we can fix in cluster manager for this. But please feel free to reopen if you feel otherwise and have any suggestions or advice.
