### ISSUE TITLE
netmaster IP address issue in cluster setup done using make demo target

### ISSUE THREAD

**Issue by vishal-j** [contiv/cluster#151]
Create vagrant cluster setup using make demo. Forward netmaster port 9999 on cluster-node1
Create network through UI. UI talks to netmaster on cluster-node1
ssh to cluster-node1.  netctl net list doesn't show networks. Network objects are created in etcd store, can be verified using etcdctl. It seems netctl is talking to netmaster on cluster-node2. 
Each node's netmaster  thinks it is the master because of IP address misconfiguration in etc/hosts file

**Comment by mapuri** [comment]
after talking Sukhesh, I think I understand the issue. Filed https://github.com/contiv/ansible/issues/220 to track changes in ansible, will close this once the ansible change is pushed and vendored in here.
