### ISSUE TITLE
Commissioning service-worker node failure on 'etcd' task - copy the etcd start/stop script

### ISSUE THREAD

**Issue by rkharya** [contiv/cluster#154]
Docker - 1.11.1-cs2
UCP - 1.1.0
Contiv_Cluster - v0.1-05-27-2016.08-26-41.UTC

Commissioning --service-worker node fails with following error -

TASK [etcd : copy the etcd start/stop script] **********************************
    fatal: [Docker-5-FCH19517CAT]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'service-master'"}

    NO MORE HOSTS LEFT *************************************************************
    	to retry, use: --limit @/home/cluster-admin/ansible/site.retry

    PLAY RECAP *********************************************************************
    Docker-5-FCH19517CAT       : ok=45   changed=24   unreachable=0    failed=1

Command used - clusterctl node commission Docker-5-FCH19517CAT --host-group=service-worker

[journalctl-clusterm.txt](https://github.com/contiv/cluster/files/310875/journalctl-clusterm.txt)
[clusterm-status.txt](https://github.com/contiv/cluster/files/310876/clusterm-status.txt)

**Comment by mapuri** [comment]
@rkharya I am trying to reproduce this locally and will get back to you with more info in a bit.

May I also know the version of clusterm that you are using: `clusterm --version` and `clusterctl --version` ?

**Comment by rkharya** [comment]
@mapuri - sure.

[cluster-admin@Docker-1 ~]$ clusterm --version
clusterm version v0.1-05-27-2016.08-26-41.UTC
[cluster-admin@Docker-1 ~]$ clusterctl --version
clusterctl version v0.1-05-27-2016.08-26-41.UTC

**Comment by mapuri** [comment]
@rkharya please try with the updated ansible. I have committed the fix (https://github.com/contiv/ansible/issues/226) there that will address this issue.
