### ISSUE TITLE
Proposal: implement node configuration update

### ISSUE THREAD

**Issue by mapuri** [contiv/cluster#160]
This proposal describes a way to implement configuration updates for nodes. 

### Background:
cluster-mgr provides a maintenance workflow, however it was left unimplemented initially to get a little more clear understanding of such a workflow. A few common scenarios that I have seen over period of time where a node may need configuration update are:
- upgrade package binaries by running newer version of ansible playbooks
- run a new ansible playbook to get script fixes and enhancements (like etcd scripts)
Other than the above, another scenario that is not addressed today as a **single workflow** is ability to change a node's role/host-group.

### Overview
- rename `maintenance` endpoint to `update` to more clearly bring out the behavior it supports
- In the initial implementation, `update` would involve running a cleanup followed by provision playbooks on one or more nodes
- the `update` workflow will optionally accept the `host-group` parameter that shall allow changing the host-group of the node(s) to the one specified as the parameter value.

#### node lifecycle:
On `Update`, the node(s) shall be moved to `InMaintenance` status where a cleanup followed by provision playbooks shall be run on specified nodes. 
On success, node(s) shall be moved back to `Commissioned` status.
In case of failure, the cleanup playbook shall be run again to avoid any leftover state and node(s) shall be moved to `Unallocated` status

#### managing host-group
All nodes shall be reassigned to the host-group specified by the `host-group` flag. If no flag is provided then there are two possible options:
**Option1:** the nodes shall remain in their last assigned host-group.

**Pros**:
- allows for easy update entire cluster

**Cons**:
- can be disruptive is user chooses all nodes at once. However, this can be addressed in future once we have playbook designed for rolling upgrades.
- if user specifies the optional host-group flag then it can accidentally reassign all nodes to the new host-group (especially `service-master`), see **special scenarios** below.
- behavior might be less intuitive when `host-group` flag is provided as it reassigns all nodes to same host-group but not specifying the flag keeps nodes in respective host-groups.

**Option2:** Only nodes in same host-group shall be allowed to be updated in one go i.e. the API will throw an error if user specifies nodes belonging to different host-groups.

**Pros**:
- the behavior associated with or without flag is more intuitive i.e. all nodes either retain their host-group (which is the same) or are reassigned to a new host-group.

**Cons**:
- makes it hard to upgrade entire cluster in one shot as nodes belonging to different groups can't be specified together.

Giving an ability to update the entire cluster in single workflow seems more useful to an admin, so **Option 1** is chosen for this proposal.
 
**Special scenarios**
- User tries configure/reassign all nodes as `service-worker`. This shall result in an API error

##### REST endpoint
- **POST**: /update/nodes

  **Body**: {
   "nodes" : [tag1, tag2 ...]
   "host-group" : "service-master | service-worker"
   }

   **Response**:
   - 200 : on successfully triggering of the update job and node(s) are moved to `InMaintenance` status
   - 500 : on error like special error scenario mentioned above
- **POST**: /update/node/{tag} : **this is mostly for consistency with existing endpoints**

  **Body**: {
   "host-group" : "service-master | service-worker"
   }

   **Response**:
   - 200 : on successfully triggering of the update job and node(s) are moved to `InMaintenance` status
   - 500 : on error like special error scenario mentioned above

##### CLI
- clusterctl node update [--host-group=< service-worker|service-master >] < tag >
- clusterctl nodes update [--host-group=< service-worker|service-master >] < tag1 > < tag2 > ...

/cc :
@vvb for overall proposal
@rkharya for use-case review
@vishal-j for UX

**Comment by vvb** [comment]
@mapuri
Thanks for putting our a detailed proposal and thinking through all the cases. :-)

Yes, we should stick with Option#1

However to avoid confusion, 
We should paint a picture of the resultant config,
```
	node1 => service-master
	node2 => service-worker
```
and ask user for confirmation.

In future we can also include suggestions at this stage. For e.g., if the user started with 3 master and wants to change one to slave. They would end up with just 2 masters. We could suggest, that it is probably not a safe to do so in production as the fault tolerance capability will take a big hit.


I have been wanting to discuss the `node` vs `nodes` thing for a while now.
I think we should simplify the APIs (CLI and REST) by just having `nodes` which should support a single node too.
Probably a personal preference, just wanted to know how you feel about it.

**Comment by mapuri** [comment]
thanks @vvb 

> We should paint a picture of the resultant config,
    node1 => service-master
    node2 => service-worker
 and ask user for confirmation.

This seems UX related. It's would be hard to get such interactive nature in a REST endpoint especially when we are dealing with clients other than CLI or UI. I think doing something like this as part of CLI or UI would be useful though, I am just not sure if we shall try address this in this proposal which is more inclined in bringing in update workflow. Is it ok to discuss this separately (may be have an issue in contiv-ui too)?

>I have been wanting to discuss the node vs nodes thing for a while now.
I think we should simplify the APIs (CLI and REST) by just having nodes which should support a single node too.

yes, `nodes` already supports single `node`. I had kept the single `node` related REST endpoint to keep something similar to libnetwork but I am yet to see any benefits of having to maintain two separate endpoints.  I am fine getting rid of the `node` endpoint. May be track it as an issue?

**Comment by mapuri** [comment]
I created #163 with code changes and also filed #164 to track `node` endpoint cleanup
