### ISSUE TITLE
Discover not happening after restarting the controller

### ISSUE THREAD

**Issue by pradvara** [contiv/cluster#166]
- Restarted the controller after shutdown.

- Discovery was not happening and the discovery was failing after serf was installed.

**Comment by vvb** [comment]
@pradvara this was caused because of missing iptables entries. Resolved by https://github.com/contiv/ansible/pull/247

There is an extra one-time manual step for nodes that were already discovered earlier with older ansible(serf). This is not required for new installations though,
```
sudo systemctl daemon-reload && sudo systemctl restart serf
```
