### ISSUE TITLE
Doc update request - make service_vip a parameter in the node commissioning section of install guide

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/cluster#187]
The install guide at https://github.com/contiv/cluster/blob/master/management/README.md should mention “service_vip” as a required parameter for node commissioning.

clusterctl node commission node1 --extra-vars='{"env" : {}, "control_interface": "eth1", "netplugin_if": "eth2" }' --host-group "service-master" should be changed to something like:
clusterctl node commission node1 --extra-vars='{"env" : {}, "control_interface": "eth1", "netplugin_if": "eth2", "service_vip": "192.168.2.252" }' --host-group "service-master"

**Comment by vvb** [comment]
@neelimamukiri that README does mention it..


"certain ansible variables need to be set for provisioning a node. The list of mandatory and other useful variables is provided in ansible_vars.md."

https://github.com/contiv/cluster/blob/master/management/ansible_vars.md

**Comment by mapuri** [comment]
Thanks @neelimamukiri for trying out cluster.

I will close this issue as the documentation exists. 

As @vvb described the list of mandatory variables is documented [here](https://github.com/contiv/cluster/blob/master/management/ansible_vars.md#mandatory-variables) and referenced in the command's documentation.

As of now the mandatory variables are just a few so adding them with individual commands is feasible but this list may grow in future. So I think long term it works best to document them together at one location and just reference the location every where else as today. Hope this clarifies.

Thanks again for reporting the issue. If you see documentation can be improved in other ways, feel free to raise another issue or submit a PR :)
