### ISSUE TITLE
ucp : create a local fetch directory - fails

### ISSUE THREAD

**Issue by vvb** [contiv/cluster#65]
The defaults for `ucp : create a local fetch directory` task need to be tuned for a non-vagrant environment. Vagrant environment relies on a shared directory which is mapped into the hosts.

```
INFO[0121] TASK [ucp : download and install ucp images] ***********************************
INFO[0158] changed: [ucsb-blade1-FCH185178B3]
INFO[0158]
INFO[0158] TASK [ucp : copy the ucp files to worker nodes] ********************************
INFO[0158] skipping: [ucsb-blade1-FCH185178B3] => (item=ucp-fingerprint)
INFO[0158] skipping: [ucsb-blade1-FCH185178B3] => (item=ucp-instance-id)
INFO[0158]
INFO[0158] TASK [ucp : copy the ucp start/stop script] ************************************
INFO[0159] changed: [ucsb-blade1-FCH185178B3]
INFO[0159]
INFO[0159] TASK [ucp : copy systemd units for ucp] ****************************************
INFO[0159] changed: [ucsb-blade1-FCH185178B3]
INFO[0159]
INFO[0159] TASK [ucp : start ucp] *********************************************************
INFO[0159] changed: [ucsb-blade1-FCH185178B3]
INFO[0159]
INFO[0159] TASK [ucp : create a local fetch directory if it doesn't exist] ****************
INFO[0160] fatal: [ucsb-blade1-FCH185178B3]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 22 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1458285908.47-139051334273265 `\" && echo \"` echo $HOME/.ansible/tmp/ansible-tmp-1458285908.47-139051334273265 `\" ), exited with result 1", "unreachable": true}
INFO[0160]
INFO[0160] PLAY ***************************************************************************
INFO[0160] skipping: no hosts matched
INFO[0160]
INFO[0160] PLAY ***************************************************************************
INFO[0160] skipping: no hosts matched
INFO[0160]      to retry, use: --limit @/go/src/github.com/contiv/cluster/vendor/ansible/site.retry
INFO[0160]
INFO[0160] PLAY RECAP *********************************************************************
INFO[0160] ucsb-blade1-FCH185178B3    : ok=36   changed=17   unreachable=1    failed=0
INFO[0160]
```

**Comment by mapuri** [comment]
@vvb 

sorry somehow I missed this one.

> Vagrant environment relies on a shared directory which is mapped into the hosts

Can you explain this a bit more? the fetch directory should be created locally on host running ansible. And it relative to the ansible playbook path i.e. `<playbook-dir>/fetch/ucp/`. So it is independent of whether the directory is mapped into hosts or not, as long as ansible-playbook directory exisits on the host.

This seems to have something to do with user permissions. I am wondering if this is resolved after following the recently documented baremetal deployment steps (https://github.com/contiv/cluster/blob/master/management/baremetal.md).

**Comment by vvb** [comment]
@mapuri you are right. my explanation is off..
this was resolved adding the following to /etc/ansible/ansible.cfg
remote_tmp     = /tmp

looks like there were some permission issues with the default `remote_tmp` path - $HOME/.ansible/tmp

**Comment by mapuri** [comment]
@vvb thanks for confirming.

If the `remote_tmp = /tmp` is still needed, can you please track this in `contiv/ansible` or may be just send a PR. I think we can add this setting in `https://github.com/contiv/ansible/blob/master/ansible.cfg` file itself.

**Comment by vvb** [comment]
@mapuri yes, it is needed. will raise a PR on the ansible repo.. we can close this one.

**Comment by mapuri** [comment]
cool, thanks @vvb
