### ISSUE TITLE
1st node commissioning failures @ucp-finerprint

### ISSUE THREAD

**Issue by rkharya** [contiv/cluster#68]
Fresh commissioning of 1st node through 'clusterctl node c' command fails to bring up 1st cluster node. Here are the steps performed after successful running of cleanup.yml and site.yml -

1. This is the command used for commissioning node-2(contiv-aci-scale-2) - "clusterctl node c contiv-aci-scale-2-FCH1924V2EK -e '{"env": {"ucp_bootstrap_node_name": "contiv-aci-scale-2-FCH1924V2EK"}}’"

2. Its succeeding till the task of downloading and installing UCP image -
Mar 21 22:21:53 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="TASK [swarm : start swarm] *****************************************************" Mar 21 22:21:53 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="skipping: [contiv-aci-scale-2-FCH1924V2EK]" Mar 21 22:21:53 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg= Mar 21 22:21:53 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="TASK [ucp : download and install ucp images] ***********************************" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="changed: [contiv-aci-scale-2-FCH1924V2EK]" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg=

3. Then it fails as below -

Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="TASK [ucp : copy the ucp files to worker nodes] ********************************" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="failed: [contiv-aci-scale-2-FCH1924V2EK] => (item=ucp-fingerprint) => {\"failed\": true, \"item\": \"ucp-fingerprint\", \"msg\": \"could not find src=/home/admin/cluster/vendor/ansible/fetch/ucp/ucp-fingerprint\"}" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="failed: [contiv-aci-scale-2-FCH1924V2EK] => (item=ucp-instance-id) => {\"failed\": true, \"item\": \"ucp-instance-id\", \"msg\": \"could not find src=/home/admin/cluster/vendor/ansible/fetch/ucp/ucp-instance-id\"}" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg= Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="NO MORE HOSTS LEFT *************************************************************" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="\tto retry, use: --limit @/home/admin/cluster/vendor/ansible/site.retry" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg= Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="PLAY RECAP *********************************************************************" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg="contiv-aci-scale-2-FCH1924V2EK : ok=33 changed=10 unreachable=0 failed=1 " Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=info msg= Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=error msg="configuration failed. Error: exit status 2" Mar 21 22:21:55 contiv-aci-scale-1.cisco.com clusterm[8423]: level=error msg="error handling event \"nodeConfigure: contiv-aci-scale-2-FCH1924V2EK\". Error: exit status 2”

4. Correspondingly I see docker deamon failing to start on node-2(contiv-aci-scale-2) - docker-daemon-failure.txt
[docker-daemon-failure.txt](https://github.com/contiv/cluster/files/183568/docker-daemon-failure.txt)

5. /var/log/messages has several error message related to docker - varlog–docker.txt
[varlog-docker.txt](https://github.com/contiv/cluster/files/183572/varlog-docker.txt)

6. Node-2 which was attempted for commissioning has below docker daemon errors -

[admin@contiv-aci-scale-2 ~]$ sudo journalctl -fu docker.service
-- Logs begin at Mon 2016-03-21 22:12:28 PDT. --
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: .time="2016-03-21T22:21:42.424692760-07:00" level=error msg="Failed to load container db52e0604886ff7bb344368802c91f1e4180ae48222eaa4f3d07410b9b4dd415: open /var/lib/docker/containers/db52e0604886ff7bb344368802c91f1e4180ae48222eaa4f3d07410b9b4dd415/config.v2.json: no such file or directory"
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: .time="2016-03-21T22:21:42.424724826-07:00" level=error msg="Failed to load container e88d1c4899313732930e7bf1244498685bd0647c0bdfe72afa4527dbac69d01c: open /var/lib/docker/containers/e88d1c4899313732930e7bf1244498685bd0647c0bdfe72afa4527dbac69d01c/config.v2.json: no such file or directory"
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: .time="2016-03-21T22:21:42.424755986-07:00" level=error msg="Failed to load container f05b778ebedb685fb9f22548156a34782e1991d5be188e1776bff52bdea92c79: open /var/lib/docker/containers/f05b778ebedb685fb9f22548156a34782e1991d5be188e1776bff52bdea92c79/config.v2.json: no such file or directory"
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: time="2016-03-21T22:21:42.700795361-07:00" level=info msg="Loading containers: done."
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: time="2016-03-21T22:21:42.700839112-07:00" level=info msg="Daemon has completed initialization"
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: time="2016-03-21T22:21:42.700870751-07:00" level=info msg="Docker daemon" commit=20f81dd execdriver=native-0.2 graphdriver=overlay version=1.10.3
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com systemd[1]: Started Docker Application Container Engine.
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: time="2016-03-21T22:21:42.708823416-07:00" level=info msg="API listen on /var/run/docker.sock"
Mar 21 22:21:42 contiv-aci-scale-2.cisco.com docker[5873]: time="2016-03-21T22:21:42.708861879-07:00" level=info msg="API listen on [::]:2385"
Mar 21 22:21:55 contiv-aci-scale-2.cisco.com docker[5873]: time="2016-03-21T22:21:55.067757464-07:00" level=error msg="Handler for GET /v1.15/containers/ucp-phase2/json returned error: No such container: ucp-phase2"

**Comment by mapuri** [comment]
@rkharya 

just closing the loop here, as we figured the issue was with the way `ucp_bootstrap_node_name` variable was being passed. The following command worked for you:

clusterctl node c contiv-aci-scale-2-FCH1924V2EK -e '{"ucp_bootstrap_node_name": "contiv-aci-scale-2-FCH1924V2EK"}’

closing this issue as this is working for you now.
