### ISSUE TITLE
5 nodes out of 8 node cluster becomes "Unallocated" deploying containers

### ISSUE THREAD

**Issue by rkharya** [contiv/cluster#76]
- Simple bash script was being used to deploy 1.6K containers, on a cluster already having ~900 containers deployed
- Deployment script failed with below errors -

66159766aea0f251f0cc03985830c36ffcb1bc09df459771f6bfd8c84852a153
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2531 web-997.contiv-net
fdef45b80aaa5c12b09663e21f0ef21b631d62644eec3574cd4fdd349561cb47
docker: Error response from daemon: 500 Internal Server Error: Post http://%2Frun%2Fdocker%2Fplugins%2Fnetplugin.sock/IpamDriver.RequestAddress: dial unix /run/docker/plugins/netplugin.sock: connect: connection refused.
container-web-2532 web-997.contiv-net
e708517a791b4742d01014e388961119c00ea4e6f9f61f58d17f37bef736a60b
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2533 web-997.contiv-net
5049845a375b006dc376382c7068c33f42bd5a0d4a777a29612bf313e786325a
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2534 web-997.contiv-net
1344d377562eeb55a58854791e17db3e9b7f42cd046941781e951371e5c5082d
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2535 web-997.contiv-net
8fc7386e64d26b5563f698d70ab98e1ecf43425160b1d529f9a14b89f8b17d1e
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2536 web-998.contiv-net
6ceaf071e88afe188ad0d64cd77f965fa4affab46498011ffd59d413f7adc872
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2537 web-998.contiv-net
6ad19448afa4583fc16293bef57a0e77e963a73afdbe482736f428c61a8e111d
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2538 web-998.contiv-net
78611db306f113553fe4b58120e4796cfc867b2aed42b9786d813de6df4c8a50
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2539 web-998.contiv-net
70647c8b486982bb7d3b2f7c69fc15b965667ed5fbfc7141e50a439c6dc61475
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2540 web-998.contiv-net
de530c4c5cc4a67421778012120ec705d736ccfa2f1d7c2df573ff03508d0f29
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2541 web-999.contiv-net
acd751460f9ed64e448b029dffe1193e06cbb52adeeced40de61805a68489b69
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2542 web-999.contiv-net
5de7c5d01f3ac54a5790e0151bf2fb24a66d996adbfa0c3f7ac89780a31f732a
docker: Error response from daemon: 500 Internal Server Error: Post http://%2Frun%2Fdocker%2Fplugins%2Fnetplugin.sock/IpamDriver.RequestAddress: dial unix /run/docker/plugins/netplugin.sock: connect: connection refused.
container-web-2543 web-999.contiv-net
05035bd055b5c00663c14ee761104728b240bc60d4152a3bf45eeaf2e0f81370
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2544 web-999.contiv-net
f2ff1f63c16f0665599a5ceb7a9b113057dc81a8dd10c13716ffc88f58a37826
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.
container-web-2545 web-999.contiv-net
48cda1d705554d06ec24c1c266463a326ecfc5a76763460abb2099452c838e2a
docker: Error response from daemon: 500 Internal Server Error: IpamDriver.RequestAddress: master failed to allocate address POST request failed.

Pointing out at IPAM driver issue.

- Also few of the nodes went into "Unallocated" state -

[admin@contiv-aci-scale-1 ~]$ clusterctl nodes get | egrep "inventory-name|status"
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-1-FCH1924V2EE",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-2-FCH1924V2EK",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-3-FCH1924V2F0",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-4-FCH1924V2FP",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-5-FCH1924V2FA",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-6-FCH1924V2F6",
            "status": "Allocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-7-FCH1924V2FC",
            "status": "Allocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-8-FCH1925V06J",
            "status": "Allocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-9-FCH1924V2EZ",

Have left the cluster in its current state. Pls. have a look at it.

Thanks,
~ Rajesh.

**Comment by mapuri** [comment]
the docker errors are coming from netplugin so it might be good to track it in netplugin.

As for some nodes being unallocated state, can you collect and provide output of `sudo journalctl -xu clusterm`. It might be huge, so you can create a gist and share the link here.

**Comment by rkharya** [comment]
Attaching clusterm service logs 
[clusterm-040116.txt](https://github.com/contiv/cluster/files/200236/clusterm-040116.txt)

**Comment by mapuri** [comment]
thanks @rkharya 

from the logs looks like clusterm crashed and restarted (due to #64). However, as part of service restart when it tries to recreate asset state it doesn't find the assets in `Unallocated` state (I looked for `contiv-aci-scale-2`) in collins, while the assets that were present in collins are correctly restored (here I looked for `contiv-aci-scale-7`) . I think collins might have restarted as well at some point which will make it forget all state.

Given we are going to get rid of collins soon (already tracked by #54), I don't feel we need to debug collins at this point and we can close this.

```
Mar 29 19:15:35 contiv-aci-scale-1.cisco.com clusterm[15156]: level=info msg="PLAY RECAP *********************************************************************"
Mar 29 19:15:35 contiv-aci-scale-1.cisco.com clusterm[15156]: level=info msg="contiv-aci-scale-9-FCH1924V2EZ : ok=57   changed=24   unreachable=0    failed=0   "
Mar 29 19:15:35 contiv-aci-scale-1.cisco.com clusterm[15156]: level=info msg=
Mar 30 21:30:52 contiv-aci-scale-1.cisco.com clusterm[15156]: level=info msg="Event received: {Event:member-failed Members:[{Name:ucsb-blade1 Addr:10.193.231.87 Port:7946 Tags:map[NodeAddr:10.193.231.87 NodeLabel:ucsb-blade1 NodeSerial:FCH185178B3] Status:failed ProtocolMin:1 ProtocolMax:2 ProtocolCur:2 DelegateMin:2 DelegateMax:4 DelegateCur:4}]}"
Mar 30 21:30:52 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="monitor event: {Type:Disappeared Node:0xc8204486c0}"
Mar 30 21:30:52 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="processing monitor event: {Type:Disappeared Node:0xc8204486c0}"
Mar 30 21:30:52 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="enqueued manager event: nodeDisappeared: &{label:ucsb-blade1 serial:FCH185178B3 addr:10.193.231.87}"
Mar 30 21:30:52 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="dequeued manager event: nodeDisappeared: &{label:ucsb-blade1 serial:FCH185178B3 addr:10.193.231.87}"
Mar 30 21:33:22 contiv-aci-scale-1.cisco.com clusterm[15156]: level=info msg="Event received: {Event:member-join Members:[{Name:ucsb-blade1 Addr:10.193.231.87 Port:7946 Tags:map[NodeSerial:FCH185178B3 NodeAddr:10.193.231.87 NodeLabel:ucsb-blade1] Status:alive ProtocolMin:1 ProtocolMax:2 ProtocolCur:2 DelegateMin:2 DelegateMax:4 DelegateCur:4}]}"
Mar 30 21:33:22 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="monitor event: {Type:Discovered Node:0xc820448780}"
Mar 30 21:33:22 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="processing monitor event: {Type:Discovered Node:0xc820448780}"
Mar 30 21:33:22 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="enqueued manager event: nodeDiscovered: &{label:ucsb-blade1 serial:FCH185178B3 addr:10.193.231.87}"
Mar 30 21:33:22 contiv-aci-scale-1.cisco.com clusterm[15156]: level=debug msg="dequeued manager event: nodeDiscovered: &{label:ucsb-blade1 serial:FCH185178B3 addr:10.193.231.87}"
Mar 30 21:33:22 contiv-aci-scale-1.cisco.com clusterm[15156]: panic: runtime error: invalid memory address or nil pointer dereference
...
...
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com systemd[1]: Starting Clusterm...
-- Subject: Unit clusterm.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit clusterm.service has begun starting up.
...
...
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=debug msg="response: {\"status\":\"success:ok\",\"data\":{\"ASSET\":{\"ID\":13,\"TAG\":\"contiv-aci-scale-7-FCH1924V2FC\",\"STATE\":{\"ID\":16,\"STATUS\":null,\"NAME\":\"DISCOVERED\",\"LABEL\":\"Discovered\",\"DESCRIPTION\":\"Node is alive and discovered in monitoring subsystem\"},\"STATUS\":\"Allocated\",\"TYPE\":\"SERVER_NODE\",\"CREATED\":\"2016-03-30T01:47:42\",\"UPDATED\":\"2016-03-30T02:11:42\",\"DELETED\":null},\"HARDWARE\":{\"CPU\":[],\"MEMORY\":[],\"NIC\":[],\"DISK\":[],\"BASE\":{\"DESCRIPTION\":\"\",\"PRODUCT\":\"\",\"VENDOR\":\"\",\"SERIAL\":\"\"}},\"LLDP\":{\"INTERFACES\":[]},\"IPMI\":{\"ASSET_ID\":13,\"ASSET_TAG\":\"contiv-aci-scale-7-FCH1924V2FC\",\"IPMI_USERNAME\":\"root\",\"IPMI_PASSWORD\":\"KfzwMWInYnJK52oc\",\"IPMI_GATEWAY\":\"172.16.32.1\",\"IPMI_ADDRESS\":\"172.16.32.31\",\"IPMI_NETMASK\":\"255.255.240.0\",\"ID\":13},\"ADDRESSES\":[],\"POWER\":[],\"ATTRIBS\":{}}}"
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=debug msg="collins asset: {Tag:contiv-aci-scale-7-FCH1924V2FC Status:Allocated State:{Name:DISCOVERED}}"
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=debug msg="created asset: &{client:0xc82000fbd0 name:contiv-aci-scale-7-FCH1924V2FC status:5 prevStatus:0 state:1 prevState:0}"
...
...
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=debug msg="dequeued manager event: nodeDiscovered: &{label:contiv-aci-scale-2 serial:FCH1924V2EK addr:10.193.231.44}"
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=warning msg="asset \"contiv-aci-scale-2-FCH1924V2EK\" already exists"
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=debug msg="created asset: &{client:0xc82000fbd0 name:contiv-aci-scale-2-FCH1924V2EK status:2 prevStatus:0 state:1 prevState:0}"
...
...
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=debug msg="dequeued manager event: nodeDiscovered: &{label:contiv-aci-scale-7 serial:FCH1924V2FC addr:10.193.231.64}"
Mar 30 21:33:32 contiv-aci-scale-1.cisco.com clusterm[3906]: level=info msg="asset already in status: \"Allocated\" and state: \"Discovered\", no action required"

```
