### ISSUE TITLE
etcd restart fails on the master node

### ISSUE THREAD

**Issue by vvb** [contiv/cluster#92]
If etcd panics/stops for some reason, then a restart of it on the master node fails with the error,
`==> no peer found, failing now`

workaround is to delete: `/tmp/etcd.existing` and then restart.

Clusterctl needs to support provisioning a cluster of master nodes together. so, that we would know who the peers are. or, we need to keep track of master during incremental provisioning and re-program existing masters to make them aware of the new master nodes.

**Comment by mapuri** [comment]
now that #106 (with #111) enable support for having multi master cluster, so thought will document another possible and perhaps more graceful/acceptable solution to this issue.

If a user bootstraps a cluster with more than one master node (3 would be recommended) then as long as a few of those nodes stay up a simple restart of etcd shall work (with the need to delete the `/tmp/etcd.existing` file).

**Comment by mapuri** [comment]
closing this as it should be fixed now with https://github.com/contiv/ansible/pull/218 and https://github.com/contiv/ansible/pull/237
